### ISSUE TITLE
ファイルサーバーがダウンしている状態でアップロードをするとデータベースが破壊される

### ISSUE THREAD

**Issue by otofune** [misskey-delta/misskey-api#55]
データベースが破壊なのかは知らないけど必要な情報が抜け落ちるっぽい
```
events.js:161
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'split' of null
    at schema.options.toObject.transform (/home/misskey/api/built/db/schemas/album-file.js:30:71)
    at model.Document.$toObject (/home/misskey/api/node_modules/mongoose/lib/document.js:2125:19)
    at model.Document.toObject (/home/misskey/api/node_modules/mongoose/lib/document.js:2252:15)
    at files.map.file (/home/misskey/api/built/endpoints/album/files/stream.js:33:44)
    at Array.map (native)
    at db_1.AlbumFile.find.sort.limit.populate.exec (/home/misskey/api/built/endpoints/album/files/stream.js:33:27)
    at /home/misskey/api/node_modules/mongoose/lib/query.js:2745:18
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**Comment by otofune** [comment]
serverPathがない状態で一旦セーブされるのでnullのままうまくハンドルできてなくて削除されずに死んでるみたいなやつですね
